### ISSUE TITLE
CLS Compliance

### ISSUE THREAD

**Issue by AbleOpus** [AlexArchive/Shortcut#4]
I noticed the Modifiers type is enumerated with uint. This breaks the CLS compliance of the assembly. If this is changed to an int, the entire assembly would be CLS Compliant. Its not a big deal considering this does not break interoperability with VB, but its something to think about.

**Comment by AlexArchive** [comment]
Thanks bud.

In light of this issue I also marked the assembly with the [`ClsCompliantAttribute`](http://msdn.microsoft.com/en-us/library/system.clscompliantattribute%28v=vs.110%29.aspx) to avoid any CLS compliance issues in the future.
